/**
 * DetectionsTab — Displays multi-sensor fusion detection results
 * 
 * Fetches hotspots.geojson and report.json from /detections/
 * These files are auto-generated by the GitHub Actions pipeline
 * and committed to the repo → Vercel serves them as static files.
 * 
 * INTEGRATION: Import this into App.jsx and add to your tab routing:
 * 
 *   import DetectionsTab from "./DetectionsTab.jsx";
 *   
 *   // In your tabs array:
 *   { id: "detections", l: "AI Detections", i: "🎯" }
 *   
 *   // In your tab content rendering:
 *   {tab === "detections" && <DetectionsTab sel={sel} setSel={setSel} />}
 */

import React, { useState, useEffect } from "react";
import { MapContainer, TileLayer, CircleMarker, Popup, useMap } from "react-leaflet";
import "leaflet/dist/leaflet.css";

var T = {
  bgPrimary: "#060d14", bgCard: "#0c1a28", bgHover: "#0f2030", bgInput: "#0a1520",
  border: "#12283e", textPri: "#e0e8f0", textSec: "#8aa4be", textDim: "#4a6a8a",
  accent: "#00d4aa", accentDim: "#00d4aa22", danger: "#ff2d55", warn: "#ffaa00", info: "#4488ff",
};
var M = "'JetBrains Mono',monospace";
var S = "'Instrument Serif',Georgia,serif";

var CONF_COLORS = {
  high: { fill: "#ff2d55", stroke: "#ff2d55", radius: 10, label: "HIGH", bg: "#ff2d5518" },
  medium: { fill: "#ffaa00", stroke: "#ffaa00", radius: 7, label: "MEDIUM", bg: "#ffaa0018" },
  low: { fill: "#4488ff", stroke: "#4488ff", radius: 5, label: "LOW", bg: "#4488ff18" },
};

function FlyTo({ center, zoom }) {
  var map = useMap();
  useEffect(function () {
    if (center) map.flyTo(center, zoom || 6, { duration: 1 });
  }, [center, zoom, map]);
  return null;
}

export default function DetectionsTab({ sel, setSel }) {
  var _h = useState(null), hotspots = _h[0], setHotspots = _h[1];
  var _r = useState(null), report = _r[0], setReport = _r[1];
  var _e = useState(null), error = _e[0], setError = _e[1];
  var _f = useState("all"), filter = _f[0], setFilter = _f[1];
  var _rg = useState("all"), regionFilter = _rg[0], setRegionFilter = _rg[1];
  var _ld = useState(true), loading = _ld[0], setLoading = _ld[1];

  // Fetch detection data
  useEffect(function () {
    setLoading(true);
    Promise.all([
      fetch("/detections/hotspots.geojson").then(function (r) { return r.json(); }),
      fetch("/detections/report.json").then(function (r) { return r.json(); }),
    ]).then(function (results) {
      setHotspots(results[0]);
      setReport(results[1]);
      setLoading(false);
    }).catch(function (err) {
      setError("Failed to load detection data: " + err.message);
      setLoading(false);
    });
  }, []);

  if (loading) {
    return React.createElement("div", {
      style: { padding: 40, textAlign: "center", color: T.textDim, fontFamily: M }
    }, "Loading detection results...");
  }

  if (error) {
    return React.createElement("div", {
      style: { padding: 40, textAlign: "center", color: T.danger, fontFamily: M }
    }, error);
  }

  var features = hotspots ? hotspots.features : [];
  var meta = hotspots ? hotspots.metadata : {};

  // Apply filters
  var filtered = features.filter(function (f) {
    if (filter !== "all" && f.properties.confidence !== filter) return false;
    if (regionFilter !== "all" && String(f.properties.region_id) !== regionFilter) return false;
    return true;
  });

  var regions = report ? report.regions : [];
  var totals = report ? report.totals : { high: 0, medium: 0, low: 0 };

  var mapCenter = sel ? [sel.lat, sel.lng] : [0, 10];

  return React.createElement("div", { style: { paddingTop: 16 } },
    // Header
    React.createElement("div", {
      style: {
        display: "flex", justifyContent: "space-between", alignItems: "center",
        marginBottom: 14, flexWrap: "wrap", gap: 8
      }
    },
      React.createElement("div", null,
        React.createElement("div", { style: { fontFamily: S, fontSize: 20 } },
          "AI Detection Results"),
        React.createElement("div", { style: { fontSize: 10, color: T.textDim, fontFamily: M, marginTop: 3 } },
          "Multi-sensor fusion: Sentinel-1 SAR + Sentinel-2 Optical + Landsat Thermal")
      ),
      React.createElement("div", {
        style: { fontSize: 10, fontFamily: M, color: T.textDim, textAlign: "right" }
      },
        "Last scan: ", React.createElement("span", { style: { color: T.accent } },
          meta.generated_at ? meta.generated_at.split("T")[0] : "—"),
        React.createElement("br"),
        "Window: ", meta.current_window_days || "—", " days | Baseline: ",
        meta.baseline_period || "—"
      )
    ),

    // Stats cards
    React.createElement("div", {
      style: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(160px, 1fr))", gap: 10, marginBottom: 14 }
    },
      [
        { l: "HIGH Confidence", v: totals.high, c: T.danger, d: "3/3 sensors agree" },
        { l: "MEDIUM Confidence", v: totals.medium, c: T.warn, d: "2/3 sensors agree" },
        { l: "LOW Confidence", v: totals.low, c: T.info, d: "1/3 sensor only" },
        { l: "Total Detections", v: totals.high + totals.medium + totals.low, c: T.accent, d: "All confidence levels" },
      ].map(function (s, i) {
        return React.createElement("div", {
          key: i,
          style: {
            background: T.bgCard, border: "1px solid " + T.border, borderRadius: 10,
            padding: 14, borderLeft: "4px solid " + s.c
          }
        },
          React.createElement("div", {
            style: { fontSize: 9, color: T.textDim, fontFamily: M, textTransform: "uppercase", letterSpacing: "0.08em" }
          }, s.l),
          React.createElement("div", {
            style: { fontSize: 28, fontWeight: 700, color: s.c, fontFamily: M, margin: "6px 0 2px" }
          }, s.v),
          React.createElement("div", { style: { fontSize: 9, color: T.textDim } }, s.d)
        );
      })
    ),

    // Filters
    React.createElement("div", {
      style: { display: "flex", gap: 6, marginBottom: 12, flexWrap: "wrap", alignItems: "center" }
    },
      React.createElement("span", {
        style: { fontSize: 10, color: T.textDim, fontFamily: M, marginRight: 4 }
      }, "Filter:"),
      ["all", "high", "medium", "low"].map(function (f) {
        var cc = CONF_COLORS[f] || { fill: T.accent, label: "ALL" };
        return React.createElement("button", {
          key: f,
          onClick: function () { setFilter(f); },
          style: {
            padding: "5px 12px", borderRadius: 6, fontFamily: M, fontSize: 10, fontWeight: 700,
            cursor: "pointer", border: filter === f ? "1px solid " + (cc.fill || T.accent) : "1px solid " + T.border,
            background: filter === f ? (cc.bg || T.accentDim) : T.bgInput,
            color: filter === f ? (cc.fill || T.accent) : T.textDim,
          }
        }, f === "all" ? "ALL (" + features.length + ")" : (cc.label || f) + " (" + features.filter(function (ft) { return ft.properties.confidence === f; }).length + ")");
      }),

      React.createElement("span", {
        style: { fontSize: 10, color: T.textDim, fontFamily: M, marginLeft: 12, marginRight: 4 }
      }, "Region:"),
      React.createElement("select", {
        value: regionFilter,
        onChange: function (e) { setRegionFilter(e.target.value); },
        style: {
          borderRadius: 6, background: T.bgInput, color: T.textPri,
          border: "1px solid " + T.border, padding: "5px 10px", fontFamily: M, fontSize: 10
        }
      },
        React.createElement("option", { value: "all" }, "All Regions"),
        regions.map(function (r) {
          return React.createElement("option", { key: r.id, value: String(r.id) },
            r.name + " (" + (r.detections.high + r.detections.medium + r.detections.low) + ")");
        })
      ),

      React.createElement("span", {
        style: { marginLeft: "auto", fontSize: 10, color: T.accent, fontFamily: M, fontWeight: 600 }
      }, filtered.length + " hotspots shown")
    ),

    // Map with detection overlay
    React.createElement("div", {
      style: {
        background: T.bgCard, border: "1px solid " + T.border, borderRadius: 10,
        padding: 8, marginBottom: 14
      }
    },
      React.createElement(MapContainer, {
        center: mapCenter, zoom: sel ? 8 : 3, maxZoom: 21, minZoom: 2,
        style: { width: "100%", height: 500, borderRadius: 8, border: "1px solid " + T.border },
        scrollWheelZoom: true, zoomControl: true,
      },
        React.createElement(FlyTo, { center: mapCenter, zoom: sel ? 8 : 3 }),

        // Base layer
        React.createElement(TileLayer, {
          url: "https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}",
          attribution: "Google", maxZoom: 21
        }),

        // Detection markers
        filtered.map(function (f, i) {
          var p = f.properties;
          var coords = f.geometry.coordinates;
          var cc = CONF_COLORS[p.confidence] || CONF_COLORS.low;
          return React.createElement(CircleMarker, {
            key: i,
            center: [coords[1], coords[0]],
            radius: cc.radius,
            pathOptions: {
              color: cc.stroke, fillColor: cc.fill, fillOpacity: 0.7,
              weight: 2, opacity: 0.9
            }
          },
            React.createElement(Popup, { maxWidth: 260 },
              React.createElement("div", {
                style: { fontFamily: "'DM Sans',sans-serif", fontSize: 12, lineHeight: 1.7, minWidth: 200 }
              },
                React.createElement("div", {
                  style: {
                    fontSize: 10, fontWeight: 700, textTransform: "uppercase",
                    color: cc.fill, background: cc.bg, padding: "3px 8px",
                    borderRadius: 4, display: "inline-block", marginBottom: 6
                  }
                }, cc.label + " CONFIDENCE"),
                React.createElement("br"),
                React.createElement("strong", null, p.region_name),
                React.createElement("br"),
                "Type: ", p.mining_type,
                React.createElement("br"),
                "Coords: ", coords[1].toFixed(4), "\u00b0, ", coords[0].toFixed(4), "\u00b0",
                React.createElement("br"),
                "Detected: ", p.detected_at
              )
            )
          );
        })
      )
    ),

    // Region breakdown table
    React.createElement("div", {
      style: {
        background: T.bgCard, border: "1px solid " + T.border, borderRadius: 10, padding: 16
      }
    },
      React.createElement("div", {
        style: { fontFamily: S, fontSize: 16, marginBottom: 12 }
      }, "Region Breakdown"),
      React.createElement("div", { style: { display: "grid", gap: 6 } },
        regions.map(function (r) {
          var total = r.detections.high + r.detections.medium + r.detections.low;
          return React.createElement("div", {
            key: r.id,
            style: {
              display: "grid", gridTemplateColumns: "1.5fr 0.5fr 0.5fr 0.5fr 0.5fr 2fr",
              gap: 8, padding: "10px 12px", background: T.bgInput,
              borderRadius: 6, alignItems: "center", fontSize: 11
            }
          },
            React.createElement("div", null,
              React.createElement("div", { style: { fontWeight: 700 } }, r.name),
              React.createElement("div", { style: { fontSize: 9, color: T.textDim } }, r.type)
            ),
            React.createElement("div", {
              style: { textAlign: "center", fontFamily: M, fontWeight: 700, color: T.danger }
            }, r.detections.high),
            React.createElement("div", {
              style: { textAlign: "center", fontFamily: M, fontWeight: 700, color: T.warn }
            }, r.detections.medium),
            React.createElement("div", {
              style: { textAlign: "center", fontFamily: M, fontWeight: 700, color: T.info }
            }, r.detections.low),
            React.createElement("div", {
              style: { textAlign: "center", fontFamily: M, fontWeight: 700, color: T.accent }
            }, total),
            React.createElement("div", {
              style: { display: "flex", gap: 4 }
            },
              // Sensor status indicators
              ["sentinel2", "sentinel1", "landsat_thermal"].map(function (sensor) {
                var status = r.sensors[sensor] || "";
                var ok = status.startsWith("OK");
                return React.createElement("span", {
                  key: sensor,
                  style: {
                    fontSize: 8, padding: "2px 6px", borderRadius: 3,
                    background: ok ? "#00d4aa15" : "#ff2d5515",
                    color: ok ? "#00d4aa" : "#ff2d55",
                    border: "1px solid " + (ok ? "#00d4aa33" : "#ff2d5533"),
                    fontFamily: M, fontWeight: 600
                  }
                }, sensor === "sentinel2" ? "S2" : sensor === "sentinel1" ? "S1" : "L8");
              })
            )
          );
        })
      ),
      // Table header labels
      React.createElement("div", {
        style: {
          display: "grid", gridTemplateColumns: "1.5fr 0.5fr 0.5fr 0.5fr 0.5fr 2fr",
          gap: 8, padding: "6px 12px", marginTop: 6, fontSize: 8,
          color: T.textDim, fontFamily: M, textTransform: "uppercase"
        }
      },
        React.createElement("span", null, "Region"),
        React.createElement("span", { style: { textAlign: "center" } }, "High"),
        React.createElement("span", { style: { textAlign: "center" } }, "Med"),
        React.createElement("span", { style: { textAlign: "center" } }, "Low"),
        React.createElement("span", { style: { textAlign: "center" } }, "Total"),
        React.createElement("span", null, "Sensors")
      )
    ),

    // Pipeline info
    React.createElement("div", {
      style: {
        marginTop: 12, padding: "12px 16px", background: T.bgInput,
        borderRadius: 8, border: "1px solid " + T.border,
        fontSize: 10, color: T.textDim, lineHeight: 1.6, fontFamily: M
      }
    },
      React.createElement("strong", { style: { color: T.accent } }, "Pipeline: "),
      "Sentinel-1 SAR (terrain/moisture change) + Sentinel-2 MSI (NDVI vegetation loss, NDBI bare soil) + Landsat 8/9 TIRS (thermal anomaly). ",
      "HIGH = all 3 sensors agree. MEDIUM = 2/3. LOW = 1/3. ",
      "Runs weekly via GitHub Actions. Data updated: ",
      React.createElement("strong", { style: { color: T.accent } },
        meta.generated_at ? meta.generated_at.split("T")[0] : "pending first run"),
      "."
    )
  );
}
